### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by tomasvanagas** [paniterka/awesome-matplotlib#1]
Hello, these links no longer work:

DataFantic - Blog
[Stylesheets](https://www.datafantic.com/the-magic-of-matplotlib-stylesheets/)
[Reproducing The Economist style](https://www.datafantic.com/making-economist-style-plots-in-matplotlib-2/)

**Comment by paniterka** [comment]
Thanks! I changed the links to point to the snapshots archived in the Wayback Machine.
